### PR TITLE
Added Hangman game in JavaScript.

### PR DESCRIPTION
**Pull request by rohansp**
Added js,css and html files for the same. related to Issue #20

### CODE REVIEW

**Comment by rohansp** [comment]
@Bhushan0246 I added hangman game in javascript. Can you review code please?

**Review by Bhushan0246 — APPROVED** [review]
Well done @rohansp

**Comment by Bhushan0246** [comment]
Don't forget to star the repo's.

**Comment by rohansp** [comment]
done

**Pull request merged**
